### ISSUE TITLE
Bug in exception handling in save_fingerprint_to_file can cause crash

### ISSUE THREAD

**Issue by wouterdb** [CheckPointSW/cp_mgmt_api_python_sdk#24]
When getting a `PermissionError` in `save_fingerprint_to_file`, the normal execution should continue. 
However, due to a bug in the log call, this causes a failure.

```
Traceback (most recent call last):
  File "/var/lib/inmanta/eb192c74-a791-4a3d-8e1f-57100ca0d8bd/agent/env/lib/python3.6/site-packages/cpapi/mgmt_api.py", line 667, in save_fingerprint_to_file
    with open(filename, 'w') as filedump:
PermissionError: [Errno 13] Permission denied: 'fingerprints.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/agent/handler.py", line 856, in execute
    self.pre(ctx, resource)
  File "/var/lib/inmanta/eb192c74-a791-4a3d-8e1f-57100ca0d8bd/agent/code/modules/checkpoint/plugins/__init__.py", line 75, in pre
    self._client.login()
  File "/var/lib/inmanta/eb192c74-a791-4a3d-8e1f-57100ca0d8bd/agent/code/modules/checkpoint/plugins/__init__.py", line 201, in login
    self._username, self._password, payload={"session-name": self.SESSION_NAME}
  File "/var/lib/inmanta/eb192c74-a791-4a3d-8e1f-57100ca0d8bd/agent/env/lib/python3.6/site-packages/cpapi/mgmt_api.py", line 198, in login
    return self._common_login_logic(credentials, continue_last_session, domain, read_only, payload)
  File "/var/lib/inmanta/eb192c74-a791-4a3d-8e1f-57100ca0d8bd/agent/env/lib/python3.6/site-packages/cpapi/mgmt_api.py", line 152, in _common_login_logic
    login_res = self.api_call("login", credentials)
  File "/var/lib/inmanta/eb192c74-a791-4a3d-8e1f-57100ca0d8bd/agent/env/lib/python3.6/site-packages/cpapi/mgmt_api.py", line 264, in api_call
    self.check_fingerprint()
  File "/var/lib/inmanta/eb192c74-a791-4a3d-8e1f-57100ca0d8bd/agent/env/lib/python3.6/site-packages/cpapi/mgmt_api.py", line 589, in check_fingerprint
    self.save_fingerprint_to_file(self.server, server_fingerprint)
  File "/var/lib/inmanta/eb192c74-a791-4a3d-8e1f-57100ca0d8bd/agent/env/lib/python3.6/site-packages/cpapi/mgmt_api.py", line 672, in save_fingerprint_to_file
    print("Couldn't open file: " + filename + " for writing.\n" + e.message, file=sys.stderr)
AttributeError: 'PermissionError' object has no attribute 'message'
```

**Comment by chkp-yaelg** [comment]
Hi @wouterdb, 

Can you please explain how did you get this error and how can we reproduce it in our lab? 

If you are working only with python 3 you can use the code from pull request #25 
later we will publish compatible code that will solve your problem in all python versions.

Regards,
Yael.

**Comment by wouterdb** [comment]
Hi @chkp-yaelg,

some context

python version: **python 3.6**
os: **centos 7**

We got this error by running this code as part of the deployment agent of the [Inmanta orchestrator](https://github.com/inmanta/inmanta). 

I think this specific error was caused because this code is executed under a system account that has very limited permissions. 
It can write to specific folders, but not to the folder it is executed in.  As we can not set the path this file is written to, it causes the first error.

@edvgui (who made #25) is a collegue of mine, we have applied his patch and it is confirmed to work. 

Thanks you for the quick repsonse,
Wouter

**Comment by chkp-yaelg** [comment]
@wouterdb and @edvgui Thanks you both for your collaboration.
I used your code and update it to be compatible to both python versions (2 and 3)
This change is available now in [release v.1.1.1](https://github.com/CheckPointSW/cp_mgmt_api_python_sdk/releases/tag/v1.1.1)
